#!/usr/bin/env sh

echo "Hooks build started"

# FIREBASE_ENV is to big to be used directly as --build-arg, creating a file which will be available for the Dockerfile
printf $FIREBASE_ENV > wind-info-firebase-adminsdk-tfxe3-aa9146d5b8.json.secret

docker build --build-arg BOT_TOKEN=$BOT_TOKEN \
    --build-arg WIND_ALERT_GROUP_CHAT_ID=$WIND_ALERT_GROUP_CHAT_ID \
    -t $IMAGE_NAME .

echo "Hooks build ended"